// <auto-generated />
using BaseProjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseProjectAPI.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20240103065610_ChangeTypePrice")]
    partial class ChangeTypePrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseProjectAPI.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasMaxLength(100)
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thám tử Conan phá án",
                            Price = 11.111000000000001,
                            Quantity = 90,
                            Title = "Conan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cuộc phiêu lưu của Goku",
                            Price = 11.1167,
                            Quantity = 90,
                            Title = "Bảy viên ngọc rồng"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chú bé đáng yêu",
                            Price = 10.0,
                            Quantity = 90,
                            Title = "Shin Cậu Bé Bút Chì"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
